const ENGLISH_QUESTIONS = [
  /* ── TOPIC 1: Types of Averages ── */
  {topic:"Types of Averages",
  q:"The Arithmetic Mean is most suitable for data that...",
  opts:["Shows sequential growth like investments","Is normally and symmetrically distributed with low variability","Handles squared quantities like electrical current","Has different levels of importance (weights) for each value"],
  ans:1,
  exp:"<strong>Arithmetic Mean</strong> is the most common average. It is suitable for data that is <em>normally and symmetrically distributed</em> and does not have extremely large outliers. For example, calculating the average test score of a class."},

  {topic:"Types of Averages",
  q:"Root Mean Square (RMS) is often used in physics and engineering, especially to handle...",
  opts:["Economic growth data","Sequential financial data","Squared quantities such as voltage or electrical current","Categorical or nominal data"],
  ans:2,
  exp:"<strong>Root Mean Square</strong> is the square root of the mean of the squares of the data values. Very useful in electrical engineering — for example, calculating the effective value of AC voltage, because AC voltage is sinusoidal and must be squared before averaging."},

  {topic:"Types of Averages",
  q:"Geometric Mean is most appropriately used for data that shows...",
  opts:["Normal distribution with small variance","Average speed or proportions","Sequential growth such as financial or economic data","Squared quantities"],
  ans:2,
  exp:"<strong>Geometric Mean</strong> is used for data that shows <em>sequential growth</em> (multiplicative growth). A classic example is calculating the average annual growth rate of an investment portfolio. Formula: GM = ⁿ√(x₁ × x₂ × ... × xₙ)."},

  {topic:"Types of Averages",
  q:"If the monthly investment growth values are 12% and 14%, what is the Geometric Mean (rounded to 2 decimals)?",
  opts:["13.00","13.50","12.96","12.50"],
  ans:2,
  exp:"GM formula for 2 values: √(12 × 14) = √168 ≈ <strong>12.96</strong>. Note: the numbers 12 and 14 are growth values (not percentages), then multiplied and rooted. √168 ≈ 12.9615."},

  {topic:"Types of Averages",
  q:"Weighted Mean is used when...",
  opts:["Data follows a normal distribution","Each data value has a different level of importance/weight","Data shows exponential growth","We want to calculate the middle value of the data"],
  ans:1,
  exp:"<strong>Weighted Mean</strong> assigns different weights to each data point according to its importance. Example: Student GPA — courses with more credits have a greater weight. Formula: x̄ = Σ(wᵢ × xᵢ) / Σwᵢ."},

  {topic:"Types of Averages",
  q:"Harmonic Mean is primarily used for data in the form of...",
  opts:["Symmetrical normal distributions","Absolute values","Ratios per unit of time or per unit (like speed, productivity)","Categorical data with many classes"],
  ans:2,
  exp:"<strong>Harmonic Mean</strong> = n / Σ(1/xᵢ). Used when data is a ratio per unit — for example, average round-trip travel speed, or average test scores of students who got different percentages from different scores."},

  {topic:"Types of Averages",
  q:"Carter Construction Company pays 14 employees @$16.50, 10 employees @$19.00, and 2 employees @$25.00 per hour. What type of average is appropriate to calculate the average wage of the 26 employees?",
  opts:["Standard Arithmetic Mean","Geometric Mean","Weighted Mean","Harmonic Mean"],
  ans:2,
  exp:"Because each group of employees has a different <em>quantity</em>, we must use the <strong>Weighted Mean</strong> where the weight = the number of employees. x̄ = (14×16.50 + 10×19.00 + 2×25.00) / 26."},

  {topic:"Types of Averages",
  q:"What is the average hourly wage of the 26 Carter Construction employees (14 @$16.50, 10 @$19.00, 2 @$25.00)?",
  opts:["$19.00","$60.50","$18.1154","$20.17"],
  ans:2,
  exp:"Weighted Mean = (14×16.50 + 10×19.00 + 2×25.00) / 26 = (231 + 190 + 50) / 26 = 471 / 26 ≈ <strong>$18.1154</strong>. This is different from the regular arithmetic mean (16.50+19.00+25.00)/3 = $20.17, because the employee distribution is not even."},

  {topic:"Types of Averages",
  q:"Calculating the average test score of a class (assuming all students are equal) is best done using...",
  opts:["Geometric Mean","Weighted Mean","Harmonic Mean","Arithmetic Mean"],
  ans:3,
  exp:"<strong>Arithmetic Mean</strong> is the right choice when all data points have the same weight. The average class test score is a classic example — all students are considered equal so just sum them up and divide by the number of students."},

  {topic:"Types of Averages",
  q:"Calculating the average 'miles per gallon' (fuel consumption) of several trips is best done using...",
  opts:["Arithmetic Mean","Geometric Mean","Harmonic Mean","Root Mean Square"],
  ans:2,
  exp:"'Miles per gallon' is a ratio. When we use the same amount of fuel for each trip (not the same distance), the <strong>Harmonic Mean</strong> provides a more accurate average because it handles ratio data per unit correctly."},

  /* ── TOPIC 2: Measures of Central Tendency & Dispersion ── */
  {topic:"Central Tendency & Dispersion",
  q:"The Median is...",
  opts:["The most frequently occurring value in the dataset","The middle value of the dataset when data is sorted ascending or descending","The average of all data values","The difference between the largest and smallest values"],
  ans:1,
  exp:"<strong>Median</strong> is the exact middle value when the data is sorted. For n odd data: value at (n+1)/2. For n even data: average of the n/2 and (n/2)+1 values. The median is not affected by extreme values (outliers)."},

  {topic:"Central Tendency & Dispersion",
  q:"The Mode is...",
  opts:["The middle value of the dataset","The arithmetic average of all values","The most frequently occurring value in the dataset","The difference between the largest and smallest values"],
  ans:2,
  exp:"<strong>Mode</strong> is the value with the highest frequency in the dataset. A dataset can have no mode, or have more than one mode (bimodal, multimodal). Mode can be used for all measurement scales including nominal."},

  {topic:"Central Tendency & Dispersion",
  q:"Variance is...",
  opts:["The square root of standard deviation","The arithmetic average of squared deviations from the mean","The difference between Q3 and Q1","The middle value of all deviations"],
  ans:1,
  exp:"<strong>Variance</strong> = Σ(xᵢ - x̄)² / (n-1) for a sample. It measures how far data is spread from the mean. The unit of variance is the unit of data squared (e.g., dollars²), which is why we often prefer to use standard deviation."},

  {topic:"Central Tendency & Dispersion",
  q:"Standard deviation is...",
  opts:["The square of the variance","The square root of the variance","The average of absolute deviations","The difference between Q3 and Q1"],
  ans:1,
  exp:"<strong>Standard Deviation</strong> = √Variance. By taking the square root of the variance, the unit returns to the original unit of the data (e.g., dollars, not dollars²). A larger standard deviation means data is spread further from the mean."},

  {topic:"Central Tendency & Dispersion",
  q:"The hourly wages of 5 part-time Home Depot employees are: $12, $20, $16, $18, $19. What is the sample variance?",
  opts:["3.16 in squared dollars","10 in dollars","3.16 in dollars","10 in squared dollars"],
  ans:3,
  exp:"Mean = (12+20+16+18+19)/5 = 85/5 = 17. Deviations²: (12-17)²=25, (20-17)²=9, (16-17)²=1, (18-17)²=1, (19-17)²=4. Σ = 40. Sample variance = 40/(5-1) = <strong>10 squared dollars</strong>. (Standard deviation = √10 ≈ 3.16 dollars)."},

  {topic:"Central Tendency & Dispersion",
  q:"Which property is TRUE about the Arithmetic Mean?",
  opts:["The Mean can be calculated for nominal data","The Mean is unique and all values are included in the calculation","The sum of deviations from the mean can be positive","The Mean can be used for any scale"],
  ans:1,
  exp:"Important properties of arithmetic mean: (1) It is <strong>unique</strong> — there is only one mean for each dataset. (2) <strong>All values</strong> are included in the calculation. (3) The sum of deviations from the mean is always = 0. (4) Only for interval and ratio scales."},

  {topic:"Central Tendency & Dispersion",
  q:"The sum of the deviation of each data value from its mean is always...",
  opts:["Positive","Negative","Zero","Equal to the standard deviation"],
  ans:2,
  exp:"This is an important mathematical property: Σ(xᵢ - x̄) = <strong>0</strong> always. This means positive and negative deviations cancel each other out. This is why for variance we square the deviations, so they don't cancel each other."},

  {topic:"Central Tendency & Dispersion",
  q:"Range is...",
  opts:["The middle value of the dataset","The most frequently occurring value","The difference between the largest and smallest values","The average of all values"],
  ans:2,
  exp:"<strong>Range</strong> = Maximum Value − Minimum Value. This is the simplest measure of dispersion, but is highly sensitive to outliers because it only considers the two extreme values."},

  {topic:"Central Tendency & Dispersion",
  q:"Interquartile Range (IQR) measures the spread of...",
  opts:["The entire dataset","The middle 50% of the data","The bottom 25% of the data","The top 25% of the data"],
  ans:1,
  exp:"<strong>IQR = Q3 − Q1</strong>, where Q1 is the first quartile (25%) and Q3 is the third quartile (75%). IQR measures the spread of the <em>middle 50%</em> of the data, so it is not affected by outliers — it's more robust than range."},

  {topic:"Central Tendency & Dispersion",
  q:"The formula for calculating standard deviation involves taking the square root of the variance. This statement is...",
  opts:["False, standard deviation is the square of the variance","True","False, standard deviation is variance divided by n","False, both are the same measure"],
  ans:1,
  exp:"<strong>True.</strong> Standard Deviation = √Variance. Logically: variance uses squared units (e.g., km²), but standard deviation returns it to original units (km) by taking the square root, making it easier to interpret."},

  /* ── TOPIC 3: Measurement Scales ── */
  {topic:"Measurement Scales",
  q:"The Nominal Scale is used for...",
  opts:["Data that can be ordered or ranked","Data with constant distance between categories","Grouping or labeling only, without order","Data with an absolute zero point"],
  ans:2,
  exp:"<strong>Nominal Scale</strong> is the lowest scale. Data is only distinguished by name/category without any order. Examples: gender, favorite color, jersey number. The only applicable operations are = or ≠."},

  {topic:"Measurement Scales",
  q:"The Ordinal Scale has the characteristic...",
  opts:["Having an absolute zero point","Data can be ordered, but the distance between ranks is unknown","Constant distance between categories but no absolute zero","For grouping only"],
  ans:1,
  exp:"<strong>Ordinal Scale</strong> has a meaningful order, but we don't know if the distance between ranks is equal. E.g., race rankings (1st, 2nd, 3rd) — we know 1st is better than 2nd, but we don't know the score difference."},

  {topic:"Measurement Scales",
  q:"The Interval Scale has the main characteristic...",
  opts:["There is an absolute zero point (zero means truly nothing)","Data can only be labeled","Constant distance between values but NO absolute zero point","All mathematical operations can be performed"],
  ans:2,
  exp:"<strong>Interval Scale</strong> has a constant and meaningful distance between values, HOWEVER it does not have an absolute zero point. Best example: Celsius temperature — 0°C does not mean 'no temperature', and 40°C is not twice as hot as 20°C."},

  {topic:"Measurement Scales",
  q:"The Ratio Scale has an advantage over the interval scale because...",
  opts:["Its data can be ordered","Constant distance between values","Has a meaningful absolute zero point","Only applies to quantitative data"],
  ans:2,
  exp:"<strong>Ratio Scale</strong> is the most complete. It has an <em>absolute zero</em> point — zero means 'truly nothing'. Examples: height, weight, income. 80 kg is indeed twice as heavy as 40 kg, because zero kg = no weight."},

  {topic:"Measurement Scales",
  q:"Temperature in Celsius (e.g., 30°C) is an example of which scale...",
  opts:["Nominal","Ordinal","Interval","Ratio"],
  ans:2,
  exp:"Celsius temperature is a classic example of an <strong>interval scale</strong>. The distance of 1°C is always constant. But 0°C does not mean there is no temperature, and 40°C is not twice as hot as 20°C — there is no absolute zero."},

  {topic:"Measurement Scales",
  q:"The number of cars sold by a salesperson (0, 5, 10, etc.) belongs to the scale...",
  opts:["Nominal","Ordinal","Interval","Ratio"],
  ans:3,
  exp:"<strong>Ratio Scale</strong>, because: (1) there is a meaningful order, (2) constant distance between values (5 cars is always the same), (3) <em>there is an absolute zero</em> — 0 cars means truly selling none. Also, 10 cars is twice as many as 5 cars."},

  {topic:"Measurement Scales",
  q:"Favorite colors (red, blue, green) belong to the scale...",
  opts:["Ratio","Interval","Ordinal","Nominal"],
  ans:3,
  exp:"Favorite colors are a <strong>nominal scale</strong>. We can only distinguish (red ≠ blue), but cannot order them (blue is not 'greater' than red) and there are no meaningful mathematical operations."},

  {topic:"Measurement Scales",
  q:"Competition rankings (1st Place, 2nd Place, 3rd Place) belong to the scale...",
  opts:["Nominal","Ordinal","Interval","Ratio"],
  ans:1,
  exp:"<strong>Ordinal Scale</strong>, because there is a meaningful order (1st Place > 2nd Place > 3rd Place). But we don't know if the difference between 1st and 2nd is the same as the difference between 2nd and 3rd — the distance is undefined."},

  {topic:"Measurement Scales",
  q:"Distance from home to campus (in km) belongs to the scale...",
  opts:["Nominal","Ordinal","Interval","Ratio"],
  ans:3,
  exp:"<strong>Ratio Scale</strong> because: there is an absolute zero (0 km = campus is in the same place), distance is meaningful, and 10 km is indeed twice as much as 5 km. All mathematical operations can be performed."},

  /* ── TOPIC 4: Descriptive vs Inferential Statistics ── */
  {topic:"Descriptive vs Inferential Statistics",
  q:"Descriptive Statistics is...",
  opts:["A method for making predictions about a population based on a sample","A method for organizing, summarizing, and presenting data informatively","A method for testing research hypotheses","A method for determining sample size"],
  ans:1,
  exp:"<strong>Descriptive Statistics</strong> is tasked with describing and summarizing existing data — creating frequency tables, histograms, calculating mean, median, standard deviation, etc. It does not make conclusions beyond the existing data."},

  {topic:"Descriptive vs Inferential Statistics",
  q:"Inferential Statistics is...",
  opts:["A way to summarize sample data with graphs","A way to create histograms and tables","A method to estimate population properties based on sample data","A way to calculate population average directly"],
  ans:2,
  exp:"<strong>Inferential Statistics</strong> uses sample data to make conclusions (inferences) about a larger population. Example: from a sample of 200 students, we estimate the average GPA of all university students."},

  {topic:"Descriptive vs Inferential Statistics",
  q:"'Descriptive statistics is primarily concerned with making predictions or inferences about a population.' This statement is...",
  opts:["True","False — what is correct is Inferential Statistics"],
  ans:1,
  exp:"<strong>False.</strong> What focuses on prediction and inference about a population is <em>Inferential Statistics</em>, not descriptive. Descriptive statistics only summarizes existing data without making further conclusions."},

  {topic:"Descriptive vs Inferential Statistics",
  q:"A Population in statistics is...",
  opts:["Some individuals selected for research","All individuals/objects that are of interest or sources of measurement","Data collected from a sample survey","A collection of descriptive statistics"],
  ans:1,
  exp:"<strong>Population</strong> is the entire set of individuals, objects, or measurements that are the focus of the research. For example, if we research Airlangga students, then all Airlangga students are the population."},

  {topic:"Descriptive vs Inferential Statistics",
  q:"A Sample in statistics is...",
  opts:["The entire researched population","A portion or part of the researched population","The average value of the population","A method of data collection"],
  ans:1,
  exp:"<strong>Sample</strong> is a part of the population chosen to represent the whole. Because it is often impossible to study the entire population, we take a representative sample and use the results to make inferences about the population."},

  {topic:"Descriptive vs Inferential Statistics",
  q:"10 Midtown Ford salespeople (data of all salespeople in that Ford) are a...",
  opts:["Sample, because it's only 10 people","Population, because it includes ALL salespeople at Midtown Ford","Subset of the automotive industry","Inferential statistic"],
  ans:1,
  exp:"The data of 10 salespeople is a <strong>population</strong> because it includes <em>all</em> salespeople at Midtown Ford — none are excluded. It's different if we only take 5 out of 10, that would be a sample."},

  /* ── TOPIC 5: Normal Distribution & Empirical Rule ── */
  {topic:"Normal Distribution & Empirical Rule",
  q:"The Empirical Rule (68-95-99.7 Rule) states that about 68% of the data in a normal distribution falls within...",
  opts:["Two standard deviations from the mean","Three standard deviations from the mean","One standard deviation from the mean","Four standard deviations from the mean"],
  ans:2,
  exp:"<strong>Empirical Rule:</strong> μ ± 1σ covers ~68% of data, μ ± 2σ covers ~95% of data, μ ± 3σ covers ~99.7% of data. This applies only to normal distributions (bell-shaped/symmetrical)."},

  {topic:"Normal Distribution & Empirical Rule",
  q:"In the Empirical Rule, about what percentage of data falls within two standard deviations from the mean?",
  opts:["68%","99.7%","95%","90%"],
  ans:2,
  exp:"<strong>μ ± 2σ ≈ 95%</strong> of data. This is the basis for the 95% confidence interval commonly used in research. It means only ~5% of data is outside this range (2.5% in each tail)."},

  {topic:"Normal Distribution & Empirical Rule",
  q:"The Empirical Rule is also known as the...",
  opts:["Chebyshev's Theorem","Hypothesis Rule","68-95-99.7 Rule","Central Limit Theorem"],
  ans:2,
  exp:"The Empirical Rule is called the <strong>68-95-99.7 Rule</strong> because these numbers are the percentages of data covered within 1σ, 2σ, and 3σ from the mean. This is different from Chebyshev's Theorem which applies to any distribution."},

  {topic:"Normal Distribution & Empirical Rule",
  q:"The Empirical Rule applies to distributions that are shaped like...",
  opts:["Uniform","Positively skewed","Normal/symmetrical (bell-shaped)","Bimodal"],
  ans:2,
  exp:"<strong>The Empirical Rule only applies to normal distributions</strong> (symmetrical bell-shaped). For non-normal distributions, we use Chebyshev's Theorem which is more conservative (applies to any distribution)."},

  {topic:"Normal Distribution & Empirical Rule",
  q:"Statement: '99% of data falls within four standard deviations of the mean.' Based on the Empirical Rule, this statement is...",
  opts:["True","False — 99.7% of data falls within THREE standard deviations, not four"],
  ans:1,
  exp:"<strong>False.</strong> According to the Empirical Rule, about <em>99.7%</em> of data is within <em>three</em> standard deviations (μ ± 3σ) — not 99% in four. So the statement is false because the standard deviation number is wrong."},

  {topic:"Normal Distribution & Empirical Rule",
  q:"In a normal distribution, the positions of the mean, median, and mode are...",
  opts:["Mean > Median > Mode","Mode > Median > Mean","Mean = Median = Mode","Cannot be determined"],
  ans:2,
  exp:"In a perfectly <strong>symmetrical</strong> normal distribution, the mean = median = mode all sit at the peak of the bell curve. This is because perfect symmetry makes the middle value, most frequent value, and average all the same."},

  {topic:"Normal Distribution & Empirical Rule",
  q:"A distribution that has a 'long tail' on the right side is called...",
  opts:["Negatively skewed","Symmetric","Positively skewed","Bimodal"],
  ans:2,
  exp:"<strong>Positively skewed</strong> = long tail on the right. Order: Mode < Median < Mean (the mean is 'pulled' to the right tail by large extreme values). Example: income distribution — most have low-middle income, few are very rich."},

  {topic:"Normal Distribution & Empirical Rule",
  q:"In a negatively skewed distribution, the correct order is...",
  opts:["Mode < Median < Mean","Mean < Median < Mode","Mean = Median = Mode","Mode > Mean > Median"],
  ans:1,
  exp:"<strong>Negatively skewed:</strong> long tail on the left → Mean < Median < Mode. The mean is pulled to the left by small extreme values. Example: easy test score distribution — most get high scores, few fail."},

  {topic:"Normal Distribution & Empirical Rule",
  q:"A distribution that has two peaks is called...",
  opts:["Unimodal","Symmetric","Negatively skewed","Bimodal"],
  ans:3,
  exp:"<strong>Bimodal</strong> means the distribution has two peaks (two modes). Example: height distribution if we mix male and female data — there will be two peaks around the average male and female heights."},

  /* ── TOPIC 6: Probability ── */
  {topic:"Probability",
  q:"Empirical Probability is a probability calculated based on...",
  opts:["Subjective judgment or individual beliefs","The proportion of similar events that occurred in the past","Theoretical calculation of the sample space","The assumption of a normal distribution"],
  ans:1,
  exp:"<strong>Empirical Probability</strong> = frequency of event / total trials. For example, if in 100 coin flips, heads appears 52 times, then the empirical probability of heads = 52/100 = 0.52. This is based on historical data/real observation."},

  {topic:"Probability",
  q:"The Law of Large Numbers states that...",
  opts:["All events have the same probability","As the number of trials increases, the empirical probability approaches its theoretical probability","Probability is always between 0 and 1","All events are mutually exclusive"],
  ans:1,
  exp:"<strong>Law of Large Numbers:</strong> the more trials performed, the closer the empirical (observed) probability gets to the theoretical probability. Example: flipping a coin 10 times might result in 7-3, but flipping 10,000 times will approach 50-50."},

  {topic:"Probability",
  q:"Two events are called Mutually Exclusive if...",
  opts:["Both can occur simultaneously","The occurrence of one does not affect the probability of the other","Both CANNOT occur at the same time","Both always occur together"],
  ans:2,
  exp:"<strong>Mutually Exclusive</strong> = cannot occur together. Example: one roll of a die cannot result in both a 3 AND a 5 simultaneously. P(A ∩ B) = 0 for mutually exclusive events."},

  {topic:"Probability",
  q:"Collectively Exhaustive means...",
  opts:["All events are independent","No two events can occur simultaneously","At least ONE event MUST occur when the experiment is performed","All events are equally likely to occur"],
  ans:2,
  exp:"<strong>Collectively Exhaustive</strong> means the set of all possible events covers all possible experimental outcomes — at least one of them MUST occur. Example: in rolling a die, {1,2,3,4,5,6} is collectively exhaustive."},

  {topic:"Probability",
  q:"Subjective Probability is...",
  opts:["Probability based on historical data","Theoretical probability of the sample space","Probability given based on individual information or beliefs","Probability that is always the same for everyone"],
  ans:2,
  exp:"<strong>Subjective Probability</strong> reflects someone's personal belief. Example: an analyst stating 'the probability of this stock rising next month is 70%' — this is based on their judgment, not a strict mathematical formula or historical data."},

  {topic:"Probability",
  q:"In a standard 52-card deck, the probability of drawing a black card AFTER drawing a red card (without replacement) is...",
  opts:["26/52 = 1/2","13/51","26/51","1/4"],
  ans:2,
  exp:"After drawing 1 red card, 51 cards remain with 26 black cards. P(black | already drew red) = <strong>26/51</strong>. This is conditional probability — the denominator changes to 51 because it's without replacement."},

  {topic:"Probability",
  q:"If p(success) = 0.5 and we want to calculate the probability of success for the first time EXACTLY on the 4th trial (Geometric Distribution), the result is...",
  opts:["6.25%","50%","12.5%","25%"],
  ans:0,
  exp:"P(X=k) = (1-p)^(k-1) × p = (0.5)³ × 0.5 = 0.5⁴ = 0.0625 = <strong>6.25%</strong>. This means the first three trials failed (0.5×0.5×0.5), and only the 4th trial succeeded (×0.5)."},

  {topic:"Probability",
  q:"Independence in the context of probability means...",
  opts:["Two events cannot occur simultaneously","The occurrence of one event DOES NOT affect the probability of another event occurring","All events have the same probability","At least one event must occur"],
  ans:1,
  exp:"<strong>Independence</strong>: P(A|B) = P(A) and P(B|A) = P(B). Meaning knowing B occurred does not change the probability of A. Example: the 1st coin flip does not affect the 2nd coin flip (each flip is always 50-50)."},

  {topic:"Probability",
  q:"An Outcome in a probability experiment is...",
  opts:["A collection of one or more experiment results","One specific result of an experiment","The probability of a certain event","The set of all possible results"],
  ans:1,
  exp:"<strong>Outcome</strong> is one specific result of an experiment. For example, in rolling a die, 'rolling a 4' is one outcome. An 'Event' can be a collection of several outcomes, e.g., 'rolling an even number' = {2,4,6}."},

  {topic:"Probability",
  q:"The probability of an event always falls in the range of...",
  opts:["0 to 100","Negative infinity to positive infinity","0 to 1 (inclusive)","1 to 100"],
  ans:2,
  exp:"Probability axioms: <strong>0 ≤ P(A) ≤ 1</strong>. P(A)=0 means the event is impossible; P(A)=1 means the event is certain. There are no negative probabilities or probabilities greater than 1."},

  /* ── TOPIC 7: Confidence Interval ── */
  {topic:"Confidence Interval",
  q:"Research in economics and business most commonly uses a confidence interval of...",
  opts:["90%","95%","35%","99%"],
  ans:1,
  exp:"<strong>95%</strong> is the most commonly used confidence interval in economics and business research. This means we are 95% confident that the calculated interval contains the true population parameter (population mean, proportion, etc.)."},

  {topic:"Confidence Interval",
  q:"A 95% confidence interval is interpreted as...",
  opts:["The null hypothesis is 95% true","95% of sample data is within this interval","If this procedure were repeated many times, 95% of the resulting intervals would contain the population parameter","There is a 5% chance the sample is wrong"],
  ans:2,
  exp:"Correct interpretation: if we take many samples and create a CI for each, then <strong>95% of those CIs will contain the true population parameter</strong>. CI is not a statement about the probability of the parameter, but about the procedure."},

  {topic:"Confidence Interval",
  q:"The average statistics score of Airlangga accounting students is calculated from a sample. This value is called...",
  opts:["Standard deviation","Confidence interval","Point estimate","Error term"],
  ans:2,
  exp:"<strong>Point Estimate</strong> is a single (point) value used as an estimate of a population parameter. Example: x̄ (sample mean) is the point estimate for μ (population mean). It differs from an interval estimate which provides a range of values."},

  {topic:"Confidence Interval",
  q:"When the POPULATION standard deviation is unknown, the distribution used for confidence intervals is...",
  opts:["Z Distribution (Normal)","T Distribution (Student's t)","Chi-Square Distribution","F Distribution"],
  ans:1,
  exp:"If population σ is unknown (practically almost always), we use the <strong>t distribution</strong> (Student's t) with (n-1) degrees of freedom. The t distribution is 'fatter' in its tails, resulting in a wider CI — reflecting the additional uncertainty because σ is unknown."},

  {topic:"Confidence Interval",
  q:"When the POPULATION standard deviation is known, the distribution used for confidence intervals is...",
  opts:["T Distribution","F Distribution","Z Distribution (Standard Normal)","Chi-Square Distribution"],
  ans:2,
  exp:"If population σ is <strong>known</strong>, use the <strong>Z distribution</strong> (standard normal distribution). This rarely happens in practice — usually only if the population is very large and has been studied before, or n is very large (n > 30) as an approximation."},

  {topic:"Confidence Interval",
  q:"An article states the average selling time of properties in Airlangga Residence is 60 days. You take a sample of 20 houses and find an average of 65 days, with a 95% CI = [62, 68] days. The most accurate interpretation is...",
  opts:["Your statistical calculation is wrong","The population average selling time is between 62 and 68 days","The average selling time is exactly 65 days","The newspaper article is correct (60 days)"],
  ans:1,
  exp:"A CI of [62, 68] days means we are 95% confident the <strong>population</strong> average selling time (all houses in Airlangga Residence) is between 62 and 68 days. Because 60 days is not within this interval, there is an indication that the article's claim needs to be confirmed."},

  {topic:"Confidence Interval",
  q:"For a two-tailed test with a 95% confidence interval, what is the level of significance (α)?",
  opts:["0.10","0.05","0.01","0.025"],
  ans:1,
  exp:"95% CI → α = 1 - 0.95 = 0.05. For a two-tailed test, α is divided by two: <strong>α/2 = 0.025 in each tail</strong>. The critical z value for a 95% two-tailed CI is ±1.96. Relationship: CI% = 100(1-α)%."},

  {topic:"Confidence Interval",
  q:"If the confidence interval used is 90%, then the level of significance for a two-tailed test is...",
  opts:["0.05","0.10","0.01","0.90"],
  ans:1,
  exp:"90% CI → α = 1 - 0.90 = <strong>0.10</strong>. For two-tailed: α/2 = 0.05 in each tail. Critical z value = ±1.65. A smaller CI (e.g., 90% vs 95%) means the interval is narrower but the confidence level is lower."},

  {topic:"Confidence Interval",
  q:"The larger the sample size (n), the width of the confidence interval will...",
  opts:["Get wider","Get narrower (more precise)","Remain the same","Change unpredictably"],
  ans:1,
  exp:"The width of the CI depends on the margin of error = z × σ/√n. Because n is in the denominator under the square root, as n gets larger → SE = σ/√n gets smaller → CI gets <strong>narrower (more precise)</strong>. This is why studies with large samples are more reliable."},

  /* ── TOPIC 8: Hypothesis Testing ── */
  {topic:"Hypothesis Testing",
  q:"The Null Hypothesis (H₀) in hypothesis testing is...",
  opts:["The hypothesis we want to prove true","The hypothesis stating there is no change, no difference, or no effect","The final conclusion of the test","The hypothesis that is definitely true"],
  ans:1,
  exp:"<strong>H₀ (Null Hypothesis)</strong> always states the 'status quo' — no difference, no effect, or the parameter value equals a certain value. Example: H₀: μ = 60 (the average is not different from 60). We try to gather evidence to REJECT H₀."},

  {topic:"Hypothesis Testing",
  q:"The Alternative Hypothesis (H₁) in hypothesis testing is...",
  opts:["The hypothesis we always reject","The hypothesis stating there is a change, difference, or effect","The hypothesis that is definitely false","The same as H₀"],
  ans:1,
  exp:"<strong>H₁ (Alternative Hypothesis)</strong> is the hypothesis we want to prove — stating there is a change/difference/effect. H₁ can take the form of ≠ (two-tailed), > (right one-tailed), or < (left one-tailed). We reject H₀ in favor of H₁."},

  {topic:"Hypothesis Testing",
  q:"A Type I Error occurs when...",
  opts:["We accept H₀ when it should be rejected","We reject H₀ when it is actually TRUE","H₁ is proven true","The sample size is too small"],
  ans:1,
  exp:"<strong>Type I Error</strong> = 'false positive' = rejecting H₀ when it is actually true. Its probability = α (significance level). Example: a judge declares a suspect guilty, when they are actually innocent. This is 'excessive error' in rejecting."},

  {topic:"Hypothesis Testing",
  q:"A Type II Error occurs when...",
  opts:["We reject H₀ when it is actually true","We FAIL to reject H₀ when it is actually FALSE","H₁ is proven true","The critical value is incorrect"],
  ans:1,
  exp:"<strong>Type II Error</strong> = 'false negative' = failing to reject H₀ when it is actually false (it should be rejected but we don't reject it). Its probability = β. Example: a judge declares a suspect innocent, when they are actually guilty."},

  {topic:"Hypothesis Testing",
  q:"The probability of making a Type I Error is called...",
  opts:["Beta (β)","Power of the test (1-β)","Alpha (α) or Significance Level","Confidence Level"],
  ans:2,
  exp:"<strong>α (Alpha)</strong> = P(Type I Error) = significance level. It is usually set to 0.05 (5%) or 0.01 (1%) before testing. The smaller the α, the stricter the criteria to reject H₀, but the greater the risk of a Type II Error."},

  {topic:"Hypothesis Testing",
  q:"The manager of PT Heinz wants to test if the average volume of syrup bottles is DIFFERENT from 660 ml. The correct hypotheses are...",
  opts:["H₀: μ > 660; H₁: μ ≤ 660","H₀: μ = 660; H₁: μ ≠ 660 (two-tailed)","H₀: μ = 660; H₁: μ > 660 (one-tailed)","H₀: μ ≠ 660; H₁: μ = 660"],
  ans:1,
  exp:"The keyword 'DIFFERENT' → <strong>two-tailed test</strong>: H₁: μ ≠ 660. We don't know the direction of the difference (could be more or less). H₀ always contains an equality sign (=), and H₁ contains ≠, >, or <."},

  {topic:"Hypothesis Testing",
  q:"The manager wants to test if the average volume of bottles is MORE THAN 660 ml. The correct alternative hypothesis (H₁) is...",
  opts:["H₁: μ ≠ 660","H₁: μ < 660","H₁: μ > 660","H₁: μ = 660"],
  ans:2,
  exp:"The keyword 'more than' → <strong>one-tailed right test</strong>: H₁: μ > 660. The rejection region is only in the right tail of the distribution. This is used when we have strong reason to suspect a change in only one direction."},

  {topic:"Hypothesis Testing",
  q:"A one-tailed test (right tail) has the H₀ rejection region in...",
  opts:["Both tails of the distribution","Only the left tail","Only the right tail","The middle of the distribution"],
  ans:2,
  exp:"<strong>One-tailed right test:</strong> the rejection region is in the right tail. If the test statistic value (z or t) is greater than the critical value, reject H₀. Used when H₁ is of the form '> ' (greater than). The entire α is on one side."},

  {topic:"Hypothesis Testing",
  q:"A two-tailed test has the H₀ rejection region in...",
  opts:["Only the right tail","Only the left tail","Both tails of the distribution (left and right)","The middle of the distribution"],
  ans:2,
  exp:"<strong>Two-tailed test:</strong> the rejection region is in both tails. α is divided in two (α/2 in each side). There are two critical values: ±. Used when H₁ is of the form '≠' (different from). Example: for α=0.05, critical z value = ±1.96."},

  {topic:"Hypothesis Testing",
  q:"If the POPULATION standard deviation is known, the one-sample statistical test formula is...",
  opts:["t = (x̄ − μ) / (s/√n)","z = (x̄ − μ) / (σ/√n)","t = (x̄₁ − x̄₂) / SE","F = s₁²/s₂²"],
  ans:1,
  exp:"<strong>z = (x̄ − μ₀) / (σ/√n)</strong> is used when σ (population standard deviation) is known. The denominator is σ/√n = standard error of the mean. The z result shows how many standard deviations x̄ is from the hypothesized μ₀."},

  {topic:"Hypothesis Testing",
  q:"If the POPULATION standard deviation is unknown, the one-sample statistical test formula is...",
  opts:["z = (x̄ − μ) / (σ/√n)","t = (x̄ − μ) / (s/√n)","z = (p̂ − p) / √(pq/n)","χ² = Σ(O−E)²/E"],
  ans:1,
  exp:"<strong>t = (x̄ − μ₀) / (s/√n)</strong> is used when σ is unknown and replaced with s (sample standard deviation). Degrees of freedom = n−1. The t distribution has thicker tails than z, reflecting the additional uncertainty."},

  {topic:"Hypothesis Testing",
  q:"The Degree of Freedom (df) for a one-sample t-test with n = 26 is...",
  opts:["26","25","27","24"],
  ans:1,
  exp:"For a one-sample t-test: <strong>df = n − 1 = 26 − 1 = 25</strong>. Degrees of freedom reflects the number of values that are 'free' to vary after we estimate the mean from the data. As df increases, the t distribution approaches a normal distribution."},

  {topic:"Hypothesis Testing",
  q:"Claims Division case: n=26, x̄=Rp56.4, s=Rp10, df=25, critical value t=-2.49 (α=1%, one-tail left), calculated t=−1.82. The conclusion is...",
  opts:["H₀ is rejected, there is evidence that costs have decreased","Not enough evidence to reject H₀","H₁ is definitively proven true","A Type II Error has definitely occurred"],
  ans:1,
  exp:"Calculated t = −1.82, critical value for one-tail left = −2.49. Because |−1.82| < |−2.49|, the calculated t <em>does not fall</em> into the rejection region. Conclusion: <strong>not enough evidence to reject H₀</strong>. We cannot claim a significant cost decrease yet."},

  {topic:"Hypothesis Testing",
  q:"A significance level of 5% (α = 0.05) means...",
  opts:["We are 95% certain H₀ is true","There is a 5% probability of making a Type I Error if H₀ is actually true","There is a 5% probability of a Type II Error","The CI is 5%"],
  ans:1,
  exp:"<strong>α = 0.05</strong> means we are willing to accept a 5% risk of incorrectly rejecting H₀ (Type I Error). This is established BEFORE testing. Choosing a small α (0.01) means being more conservative (harder to reject H₀), but the risk of Type II Error increases."},

  {topic:"Hypothesis Testing",
  q:"To reduce the risk of BOTH Type I and Type II Errors simultaneously, the best way is to...",
  opts:["Decrease the significance level (α)","Increase the significance level (α)","Increase the sample size (n)","Use a two-tailed test"],
  ans:2,
  exp:"There is a <em>trade-off</em> between Type I and Type II errors — decreasing α reduces Type I but increases Type II, and vice versa. The only way to reduce both <strong>simultaneously</strong> is by <strong>increasing the sample size (n)</strong>."},

  {topic:"Hypothesis Testing",
  q:"The data used for one-sample and two-sample hypothesis testing MUST...",
  opts:["Be on a nominal scale","Be on an ordinal scale","Be normally distributed","Have the same variance"],
  ans:2,
  exp:"The basic assumption of t and z tests is that the data must come from a <strong>normally distributed</strong> population (or n is large enough so that the Central Limit Theorem applies). Violating this assumption can make the test results invalid."},

  {topic:"Hypothesis Testing",
  q:"In the PT Heinz case (n=50, μ₀=660, known σ=7, x̄=663), the statistical test formula used is...",
  opts:["t-test because n is small","z-test because population σ is known","t-test because the distribution is not normal","F-test because there are two samples"],
  ans:1,
  exp:"Because the population σ = 7 ml is <strong>known</strong>, we use the <strong>z-test</strong>: z = (663 − 660) / (7/√50) = 3 / 0.99 ≈ 3.03. The critical value for α=5% two-tailed is ±1.96. Since 3.03 > 1.96, H₀ is rejected."},

  /* ── TOPIC 9: Two Samples & Paired Samples ── */
  {topic:"Two Sample Tests",
  q:"A sales manager compares sales by men (μ=1400, σ=200) and women (μ=1500, σ=250). The population standard deviations are known. The appropriate statistical test is...",
  opts:["One-sample t-test","Two-sample z-test","Paired t-test","Chi-square test"],
  ans:1,
  exp:"Because the <strong>population standard deviations are known</strong> and we are comparing <strong>two independent samples</strong>, the <strong>two-sample z-test</strong> is used. Formula: z = (x̄₁ − x̄₂) / √(σ₁²/n₁ + σ₂²/n₂)."},

  {topic:"Two Sample Tests",
  q:"The manager wants to test if women's sales are GREATER THAN men's. The H₀ rejection region is in...",
  opts:["Both tails (two-tailed)","The left tail","The right tail","The middle of the distribution"],
  ans:2,
  exp:"H₁: μ_women > μ_men → this is a <strong>one-tailed right test</strong>. The rejection region is in the right tail. We only reject H₀ if the difference is large enough in the positive direction (women are higher)."},

  {topic:"Two Sample Tests",
  q:"Which statement is INCORRECT regarding the Sales Manager case (testing women > men)?",
  opts:["The samples are independent","The statistical test used is a z-test","The H₀ rejection region is in the right tail","The H₀ rejection region is in BOTH the left and right tails"],
  ans:3,
  exp:"Option d) is wrong because 'rejection region in both tails' is characteristic of a two-tailed test, whereas this test is <strong>one-tailed (right)</strong> because H₁: μ_women > μ_men. Options a, b, and c are all correct."},

  {topic:"Two Sample Tests",
  q:"To evaluate the effectiveness of a course, an investigator tests the pre-test (before) and post-test (after) scores of the SAME students. This type of sample is...",
  opts:["Independent samples","Paired samples (dependent)","Simple random samples","Stratified samples"],
  ans:1,
  exp:"Pre-test and post-test scores are taken from <strong>the same students</strong> at two different times → these are <strong>paired samples</strong>. The analysis uses a paired t-test, not an independent sample t-test."},

  {topic:"Two Sample Tests",
  q:"Statement: 'Testing pre-test and post-test scores on the same students involves INDEPENDENT samples.' This is...",
  opts:["True","False — these are paired/dependent samples"],
  ans:1,
  exp:"<strong>False.</strong> Pre-test and post-test on the same students are <em>paired samples (dependent)</em>, not independent. Two samples are independent if the members of one sample have no relationship to the members of the other sample."},

  /* ── TOPIC 10: Frequency Tables & Distributions ── */
  {topic:"Frequency Tables & Distributions",
  q:"A histogram is a graph where...",
  opts:["Data values are plotted randomly","Classes are marked on the horizontal axis and class frequencies on the vertical axis","Categorical data is depicted as separate bars","It is only used for nominal data"],
  ans:1,
  exp:"A <strong>Histogram</strong> is a bar graph for continuous data. Classes (intervals of values) are on the horizontal axis, and frequencies/relative frequencies on the vertical axis. The bars are adjacent (no gaps), unlike a bar chart for categorical data."},

  {topic:"Frequency Tables & Distributions",
  q:"Relative Frequency is...",
  opts:["The absolute number of values in each class","Absolute frequency divided by total frequency","Frequencies ordered from smallest to largest","Cumulative frequency"],
  ans:1,
  exp:"<strong>Relative Frequency</strong> = Class Frequency / Total Frequency. The result is a proportion (0 to 1) or percentage (0 to 100%). It is useful for comparing distributions between groups of different sizes."},

  {topic:"Frequency Tables & Distributions",
  q:"From 1000 Minnesota residents: 100 like winter, 300 spring, 400 summer, 200 fall. The relative frequency for winter is...",
  opts:["100","10%","1.0","0.10 (or 10%)"],
  ans:3,
  exp:"Relative frequency = 100/1000 = <strong>0.10</strong> (or 10%). The sum of all relative frequencies must = 1.00 (100%). Check: 0.10 + 0.30 + 0.40 + 0.20 = 1.00 ✓."},

  {topic:"Frequency Tables & Distributions",
  q:"In the Applewood Auto Group frequency table (profit <$600=8, $600-$1000=11, $1000-$1400=23...), the cumulative frequency of 'profit less than $1000' is...",
  opts:["8","11","19","34"],
  ans:2,
  exp:"Cumulative frequency 'less than $1000' = all classes below $1000 = 8 + 11 = <strong>19</strong>. Cumulative frequency is the sum of all frequencies from the first class up to the specified class."},

  {topic:"Frequency Tables & Distributions",
  q:"The cumulative frequency of 'profit less than $2600' in the Applewood data (8+11+23+38+45+32=157, then +19=176) is...",
  opts:["157","176","19","180"],
  ans:0,
  exp:"Classes up to $2600 (exclusive): $200-600=8, $600-1000=11, $1000-1400=23, $1400-1800=38, $1800-2200=45, $2200-2600=32. Total = 8+11+23+38+45+32 = <strong>157</strong>."},

  {topic:"Frequency Tables & Distributions",
  q:"Wellstone Inc. survey (Bright white=130, Metallic black=104, Magnetic lime=325, Tangerine orange=455, Fusion red=286, Total=1300). If 1 million units are produced, the number of bright white produced is...",
  opts:["80,000","100,000","220,000","130,000"],
  ans:1,
  exp:"Proportion of bright white = 130/1300 = 0.10 = 10%. Production = 0.10 × 1,000,000 = <strong>100,000 units</strong>. Magnetic lime = 325/1300 = 25% → 250,000 units."},

  /* ── TOPIC 11: Venn Diagrams ── */
  {topic:"Sets & Venn Diagrams",
  q:"Given A = {1,2,3,4,5,6} and B = {1,2,3,4,5,6,7,8,9,10}. The correct relationship between A and B is...",
  opts:["A and B are unrelated","A = B (exactly the same)","A is a subset of B (A ⊂ B)","B is a subset of A"],
  ans:2,
  exp:"All elements of A ({1,2,3,4,5,6}) are also in B, and B has additional elements (7,8,9,10). Thus <strong>A ⊂ B</strong> (A is a proper subset of B). The correct Venn Diagram shows circle A completely inside circle B."},

  {topic:"Sets & Venn Diagrams",
  q:"A Venn Diagram illustrating A ⊂ B (A is a subset of B) shows...",
  opts:["Two partially intersecting circles","Two separate (non-intersecting) circles","Circle A completely inside circle B","Two circles of the same size that perfectly overlap"],
  ans:2,
  exp:"For A ⊂ B: circle A is <strong>completely inside</strong> the larger circle B. All members of A are also members of B, but B has members that are not members of A."},

  {topic:"Sets & Venn Diagrams",
  q:"The Union A ∪ B means...",
  opts:["Elements that are in A AND B (both)","Elements that are in A OR B (or both)","Elements that are only in A","Elements outside A and B"],
  ans:1,
  exp:"<strong>A ∪ B</strong> (Union) = all elements that are in A, in B, or in both. In logic: A OR B. P(A ∪ B) = P(A) + P(B) − P(A ∩ B). For mutually exclusive events: P(A ∪ B) = P(A) + P(B)."},

  {topic:"Sets & Venn Diagrams",
  q:"The Intersection A ∩ B means...",
  opts:["Elements that are in A or B","Elements that are in A AND B (both at the same time)","Elements that are only in A","All elements outside A and B"],
  ans:1,
  exp:"<strong>A ∩ B</strong> (Intersection) = elements that are in A AND B simultaneously. In probability: P(A ∩ B) = P(A) × P(B|A) = P(A) × P(B) if A and B are independent."},

  /* ── TOPIC 12: Mixed Application Questions ── */
  {topic:"Mixed Applications",
  q:"10 Midtown Ford salespeople sold: 15, 23, 4, 19, 18, 10, 10, 8, 28, 19 cars. Their Arithmetic mean is...",
  opts:["154","14","15.4","19"],
  ans:2,
  exp:"Mean = (15+23+4+19+18+10+10+8+28+19) / 10 = 154 / 10 = <strong>15.4</strong>. Don't confuse this by just summing them up (154) — that has not been divided by the number of data points."},

  {topic:"Mixed Applications",
  q:"Statement: 'To reduce the risk of BOTH Type I Error AND Type II Error simultaneously, an investigator simply needs to increase the sample size.' This is...",
  opts:["True","False — adding samples DOES NOT directly reduce Type I Error"],
  ans:1,
  exp:"Actually, this needs nuanced explanation: increasing n does reduce Type II Error (increases power). However, Type I Error (α) is set by the researcher, not directly affected by n. Nevertheless, in the context of this specific test, the answer is <strong>False</strong> — because Type I Error is controlled by choosing α, not n."},

  {topic:"Mixed Applications",
  q:"When the confidence interval used is 99%, the level of significance for a two-tailed test is...",
  opts:["0.10","0.05","0.01","0.001"],
  ans:2,
  exp:"99% CI → α = 1 − 0.99 = <strong>0.01</strong>. For two-tailed: α/2 = 0.005 in each tail. Critical z value ≈ ±2.58. A 99% CI provides a wider interval than 95%, but we are more certain the interval contains the population parameter."},

  {topic:"Mixed Applications",
  q:"In the Heinz case (n=50, σ=7, x̄=663, μ₀=660), calculated z ≈ 3.03. With α=5% two-tailed (critical_z=±1.96), the conclusion is...",
  opts:["H₀ is accepted — the average is not different from 660 ml","H₀ is rejected — there is evidence the average is different from 660 ml","Not enough information to decide","A Type II Error occurred"],
  ans:1,
  exp:"Calculated z = 3.03 > critical z = 1.96 → calculated z falls into the rejection region. Conclusion: <strong>Reject H₀</strong>. There is statistical evidence that the average bottle volume is different from 660 ml at the 5% significance level."},

  {topic:"Mixed Applications",
  q:"The Heinz case with a one-tailed right test (manager wants to know if bottle volume is MORE than 660 ml): critical_z = 1.65 (α=5%). With calculated z = 3.03, the conclusion is...",
  opts:["H₀ is accepted","H₀ is rejected, there is evidence bottle volume is more than 660 ml","Not enough information","H₀ is rejected because it is two-tailed"],
  ans:1,
  exp:"Calculated z = 3.03 > critical z = 1.65 → falls into the rejection region (right tail). <strong>Reject H₀</strong>. There is enough evidence that the average bottle volume is more than 660 ml at α = 5%."},

  {topic:"Mixed Applications",
  q:"Insurance Claims Division (n=26, x̄=Rp56.4, H₀: μ=60, H₁: μ<60). The manager accepts H₀. An INCORRECT interpretation is...",
  opts:["The difference between sample and population could be due to sampling error","The results show cost-cutting efforts have not yet been effective","There is sufficient evidence that cost-cutting efforts HAVE been effective","Statistics did not find a significant decrease from Rp60"],
  ans:2,
  exp:"Because H₀ is accepted (not rejected), we DO NOT have enough evidence that costs significantly decreased. So option c) is wrong — we cannot state 'there is sufficient evidence that efforts were effective'. Accepting H₀ ≠ proving H₀ is true."},

  {topic:"Mixed Applications",
  q:"In hypothesis testing, if the statistical test value (calculated t or z) is GREATER THAN the critical value in a one-tailed right test, then...",
  opts:["Accept H₀","Reject H₀","Repeat the test with a new sample","No conclusion can be made"],
  ans:1,
  exp:"<strong>Reject H₀</strong>. For a one-tailed right test: if the statistical value > critical value, it means the value falls into the rejection region (right tail). We reject H₀ and support H₁."},

  {topic:"Mixed Applications",
  q:"All of the following statements about probability are TRUE, EXCEPT...",
  opts:["Theoretical probability divides the basic theory of probability","Probability theory helps make decisions under uncertainty","Advanced techniques like Bayesian methods are useless for real-world data analysis","Probability theory is used in experimental design and surveys"],
  ans:2,
  exp:"Statement c) is false — Bayesian methods and probabilistic graphical models are very useful and increasingly used in modern machine learning and data analysis. Saying they are 'useless' is incorrect."},

  {topic:"Mixed Applications",
  q:"Which is NOT an important property of the Mean in statistics?",
  opts:["The Mean is unique (there is only one mean value)","All data values are included in the mean calculation","The sum of deviations from the mean is always zero","The Mean can be calculated for nominal-scaled data"],
  ans:3,
  exp:"The Mean <strong>cannot</strong> be calculated for nominal data (e.g., gender, color). The mean is only meaningful for <em>interval</em> or <em>ratio</em> scale data. The other three properties (a, b, c) are true for the arithmetic mean."},

  {topic:"Mixed Applications",
  q:"Quartiles divide a dataset into...",
  opts:["Two equal parts","Three equal parts","Four parts that each contain about 25% of the data","Five equal parts"],
  ans:2,
  exp:"<strong>Quartiles</strong> divide sorted data into four equally sized parts. Q1 (25%), Q2 (50% = Median), Q3 (75%). IQR = Q3 − Q1 covers the middle 50% of the data."},

  {topic:"Mixed Applications",
  q:"If it is known that CI = 90% for a two-tailed test, which statement is TRUE about the significance level?",
  opts:["Significance level = 0.90","Significance level = 0.10, and α/2 = 0.05 in each tail","Significance level = 0.05, and α/2 = 0.025","Significance level = 0.01"],
  ans:1,
  exp:"90% two-tailed CI: α = 1 − 0.90 = <strong>0.10</strong>. For two-tailed: α/2 = 0.05 on each side. Critical z value = ±1.65. This is what the PDF quiz question meant: 'two-tailed 90% → significance level 0.10.'"},

  {topic:"Mixed Applications",
  q:"The statistical method that organizes, summarizes, and presents data informatively is called...",
  opts:["Inferential Statistics","Descriptive Statistics","Probability Theory","Hypothesis Testing"],
  ans:1,
  exp:"<strong>Descriptive Statistics</strong>: describes existing data. Its tools: frequency tables, histograms, mean, median, mode, range, variance, standard deviation, etc. Its goal is to present data concisely and comprehensively."},

  {topic:"Mixed Applications",
  q:"The statistical method for estimating population properties based on a sample is called...",
  opts:["Descriptive Statistics","Inferential Statistics","Descriptive Analysis","Data Exploration"],
  ans:1,
  exp:"<strong>Inferential Statistics</strong>: makes inferences/conclusions about a population based on sample data. Includes: confidence intervals, hypothesis testing, regression analysis, ANOVA, etc."}
];
